project:
  type: website
  output-dir: docs

website:
  title: "Mirzokhidjon Yakubov"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: curriculum.qmd
        text: Curriculum
      - href: projects.qmd
        text: Projects
      - href: skills.qmd
        text: Skills
      - href: contact.qmd
        text: Contact

format:
  html:
    theme: cerulean
    toc: true
    page-layout: full
 