---
title: "Mirzokhidjon Yakubov | MBA. Student"
subtitle: "I am a graduate student at the University of Canada West who is currently studying Master of Business Administration (MBA)"
format: html
page-layout: full
---
# MIRZOKHIDJON YAKUBOV
## A Bit About Me
I’m a sixth-year Ph.D. candidate in the Department of Psychology at UC Berkeley. I am a social/cultural psychologist in the UCDREAMS lab, supervised by Dr. Arianne Eason.

As a graduate student, I have cultivated two lines of research that shed light on the causes and consequences of omission, misrepresentation, and discrimination. In the first, I study bias towards, and experiences of, LGBTQ+ people. In the second, I collaborate with Dr. Stephanie Fryberg and the Research for Indigenous Action and Social Equity (RISE) center at Northwestern University to explore the omission of Native Peoples and its consequences.

I began my research career as an undergraduate researcher at the University of British Columbia, where I conducted honors thesis projects with Dr. Frances Chen, and Dr. Toni Schmader. After graduating from UBC , I was Dr. Nicole Stephens’s lab manager at Northwestern University.
