---
title: "Resume"
format: html
toc: true
page-layout: full
---

# Education

  - **University of Southern California (USC)** – Class of 2024  
  *Master of Science in Entrepreneurship and Innovation*  
  **Cumulative GPA:** 3.68  

- **University of Pennsylvania (Wharton School)** – Class of 2023  
  *Bachelor of Science in Economics, Concentrations in Finance and Management*  
  **Cumulative GPA:** 3.5  

---

# Courses I’ve Taken

- Financial Accounting  
- Corporate Finance  
- Strategic Management  
- Venture Capital and Innovation  
- Global Business Strategy  
- Entrepreneurial Leadership  
- Data Analytics for Business  

---

# Work Experience

## Accountant – Citrin Cooperman  
*Woodland Hills, CA (Aug 2024 – Present)*  
- Member of the advisory services team for the Business Management Family Office's music practice.  

## Large Customer Sales BOLD Intern – Google  
*Chicago, IL (May 2022 – Aug 2022)*  
- Completed Sales School training on Google’s advertising platforms with Heads of Industry and Account Managers.  
- Supported Google’s largest-spending clients, focusing on YouTube and Search optimization for $1M+ marketing budgets.  
- Conducted a summer-long analysis of Google’s American Sales Associate Program and presented recommendations to leadership.  

## Entertainment Banking Intern – City National Bank  
*Beverly Hills, CA (May 2021 – Aug 2021)*  
- Participated in business management and client meetings to assess financial and investing objectives.  
- Reviewed financial statements and analyzed performance of high-net-worth individuals.  
- Spearheaded the Donor-Advised Fund initiative by creating marketing materials.  

## Corporate Finance Intern – Allied Universal  
*Tustin, CA (May 2020 – Aug 2020)*  
- Assisted the VP of Finance in monthly Vertical Reporting and expense analysis.  
- Collaborated with Pricing Analyst to create templates for a $3M security bid.  

---
# Leadership & Extracurriculars

## University of Southern California Women’s Basketball  
*Full Scholarship-Athlete, Starting Point Guard (2023–2024)*  
- Competed as a starter for the Elite 8 and PAC-12 Championship Lady Trojans team while pursuing a master’s degree.  

## University of Pennsylvania Women’s Basketball  
*Team Captain (2019–2023)*  
- Devoted 30+ hours weekly in-season and 15+ hours off-season balancing athletics with rigorous academics.  
- Earned **2× First-Team All-Ivy**, **2× First-Team All-Big 5**, and **2020 Ivy League Rookie of the Year**.  

## The Sideline Post  
*Founder & Editor-in-Chief (Apr 2020 – Present)*  
- Developed a media platform amplifying the voices of collegiate athletes.  
- Generated over **18,000 website views** and published **20+ full-length stories** in the first year.  

## Google BOLD Immersion Program  
*Participant (Jul 2021 – Aug 2021)*  
- Selected as 1 of only 60 students for a three-week Google program focused on skill-development and